# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
keys = [
  37
  38
  39
  40
]
centermap=[25.699463, -100.370624]
center=[25.694736,-100.370453]
mkr='/img/dot.png'

preloadPictures = (pictureUrls, callback) ->
  i = undefined
  j = undefined
  loaded = 0
  i = 0
  j = pictureUrls.length
  while i < j
    ((img, src) ->

      img.onload = ->
        if ++loaded == pictureUrls.length and callback
          callback()
        return

      # Use the following callback methods to debug
      # in case of an unexpected behavior.

      img.onerror = ->

      img.onabort = ->

      img.src = src
      return
    ) new Image, pictureUrls[i]
    i++
  return

# ---
# generated by js2coffee 2.0.3

preventDefault = (e) ->
  e = e or window.event
  if e.preventDefault
    e.preventDefault()
  e.returnValue = false
  return

keydown = (e) ->
  i = keys.length
  while i--
    if e.keyCode == keys[i]
      preventDefault e
      return
  return

wheel = (e) ->
  preventDefault e
  return

disable_scroll = ->
  if window.addEventListener
    window.addEventListener 'DOMMouseScroll', wheel, false
  window.onmousewheel = document.onmousewheel = wheel
  document.onkeydown = keydown
  return

enable_scroll = ->
  if window.removeEventListener
    window.removeEventListener 'DOMMouseScroll', wheel, false
  window.onmousewheel = document.onmousewheel = document.onkeydown = null
  return

# ---
# generated by js2coffee 2.0.3

showHide = (ob)->
  $('#home .slide.active').removeClass('active').addClass('out')
  setTimeout (->
    $('#home .slide.out').removeClass('out').addClass('in')
    
  ), 500
  $(ob).removeClass('in').addClass('active')
$ ->
  if window.location.pathname is '/home/site'
    $('#home').css
          'opacity': 1
    $('.bg1').css
      'display': 'none'
  if window.location.pathname is '/home/services'
    $('#servicios .servicio').each ->
      el=$(this).find('h3')
      console.log(el)
      
      elH = el.height()/2
      elT = 64-elH
      el.css
        'transform': 'translate(0px, '+elT+'px)'
      console.log(el.css('transform'))

    $('#servicios .servicio .click').on 'click', ->
      $('#servicios .servicio').removeClass 'active'
      $('#servicios .servicio').each ->
        el=$(this).find('h3')
        console.log(el)
        
        elH = el.height()/2
        elT = 64-elH
        el.css
          'transform': 'translate(0px, '+elT+'px)'
        console.log(el.css('transform'))

      $(this).parent().addClass 'active'
      $(this).parent().find('h3').css
        'transform': 'translate(0px,0px)'
      
    $('#servicios .servicio .close').on 'click', ->
      console.log 'click'
      $(this).parent().removeClass('active')
      el=$(this).parent().find('h3')
      console.log(el)
      
      elH = el.height()/2
      elT = 64-elH
      el.css
        'transform': 'translate(0px, '+elT+'px)'
  if window.location.pathname is "/home/contact"
    $('.contacto-form').height($(window).height())
    initialize = ->
      stl=[{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"simplified"}]},{"featureType":"landscape","elementType":"geometry","stylers":[{"visibility":"simplified"},{"color":"#fcfcfc"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"visibility":"simplified"},{"color":"#fcfcfc"}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"visibility":"simplified"},{"color":"#dddddd"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"visibility":"simplified"},{"color":"#dddddd"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"visibility":"simplified"},{"color":"#eeeeee"}]},{"featureType":"water","elementType":"geometry","stylers":[{"visibility":"simplified"},{"color":"#dddddd"}]}]
      mapOptions = 
        center:
          lat: centermap[0]
          lng: centermap[1]
        zoom: 15
        scrollwheel: false
        panControl: false
        streetViewControl: false
        zoomControlOptions:
          position: google.maps.ControlPosition.RIGHT_TOP
          style: google.maps.ZoomControlStyle.SMALL
      
      map = new (google.maps.Map)(document.getElementById('mapa'), mapOptions)
      contentString = '<div id="infoquiondas">' + '<div id="siteNotice">' + '</div>' + '<h1 id="firstHeading" class="firstHeading">Hammers<br/>Electromechanical</h1>' + '<div id="bodyContent">' + '<p>Blvd. Puerta del Sol 1197-A<br/>Colinas de San Jerónimo<br/>Monterrey, N.L. 21132<br/><br/>t. +52 (81) 196-80151<br/><span class="blanco">t. </span>+52 (81) 196-80152</p>' + '<a class="email-info" href="mailto:info@hammers.mx">SEND MAIL</a>'
     
      infowindow = new InfoBox
        content: contentString
        maxWidth: 300
        alignBottom: false
        # position: infolatlng
        pixelOffset: new google.maps.Size(0,-300)
        closeBoxURL: ""
        boxStyle: 
          background: "url('/img/square.png') no-repeat" 

      myLatLng = new google.maps.LatLng(center[0], center[1])
      marker = new (google.maps.Marker)(
        position: myLatLng
        map: map
        icon: mkr
        title: 'Hello World!')
      google.maps.event.addListener marker, 'click', ->
        infowindow.open map, marker
        return
      infowindow.open map, marker
      # infowindow.setPosition(infolatlng)
      map.set("styles", stl)
      $(".gm-style-iw").next("div").hide();
      return

    google.maps.event.addDomListener window, 'load', initialize

  $('.bg1 .loading').addClass 'loaded'
  preloadPictures [
    '/img/fondo-splash.jpg'
    '/img/fondo-home.jpg'
    '/img/trabajadores.png'
  ], ->
    console.log 'callback'
    $(window).load ->
      
      setTimeout (->
        $('#home').css
          'opacity': 1

        $('#categories').css({"bottom": "-160px"})
        console.log 'loaded'
        $('.bg1').css
          'opacity': 0
          'visibility': 'hidden'
        
        
        # $('.section').height($(window).height())
        $('#categories .cat-item').on 'click', (e)->
          e.preventDefault()
          obj = $(this).attr 'obj'
          showHide(obj)
          $('#home .bg').css({"opacity": 1})
          $('#home .trabajadores').css({"opacity": 0})
            
        setTimeout (->
          $('#categories').css({"bottom": "-160px"})  
        ), 1000
        setTimeout (->
          $('#about .scroll-down').css({"opacity": "0"})  
        ), 6000
        # if window.location.pathname is "/home/about"
          # disable_scroll()
          # $('#about .about-intro').on 'mousewheel', (event)-> 
            # console.log event
            # console.log(event)
            # console.log(event.offsetY)
          # if event.offsetY>1

            # $.scrollTo($('#about .about-contenido'), {
            #   offset: -80
            #   duration: 600
            #   onAfter: ->
            #     enable_scroll()
            #   })

        
      ), 3000